//定义action
export const PERFORMANCE_REQUESTING = 'PERFORMANCE_REQUESTING'
export const PERFORMANCE_REQUESTED = 'PERFORMANCE_REQUESTED'
export const PERFORMANCE_REQUESTERROR = 'PERFORMANCE_REQUESTERROR'